class Seats {
   String id,
      movieId,
      seat1,
      seat2,
      seat3,
      seat4,
      seat5,
      seat6,
      seat7,
      seat8,
      seat9,
      seat10,
      seat11,
      seat12,
      seat13,
      seat14,
      seat15,
      seat16,
      seat17,
      seat18,
      seat19,
      seat20,
      seat21,
      seat22,
      seat23,
      seat24,
      seat25,
      seat26,
      seat27,
      seat28,
      seat29,
      seat30,
      seat31,
      seat32,
      seat33,
      seat34,
      seat35,
      seat36,
      seat37,
      seat38,
      seat39,
      seat40,
      seat41,
      seat42,
      seat43,
      seat44;


  Seats(
      {this.id,
      this.movieId,
      this.seat1,
      this.seat2,
      this.seat3,
      this.seat4,
      this.seat5,
      this.seat6,
      this.seat7,
      this.seat8,
      this.seat9,
      this.seat10,
      this.seat11,
      this.seat12,
      this.seat13,
      this.seat14,
      this.seat15,
      this.seat16,
      this.seat17,
      this.seat18,
      this.seat19,
      this.seat20,
      this.seat21,
      this.seat22,
      this.seat23,
      this.seat24,
      this.seat25,
      this.seat26,
      this.seat27,
      this.seat28,
      this.seat29,
      this.seat30,
      this.seat31,
      this.seat32,
      this.seat33,
      this.seat34,
      this.seat35,
      this.seat36,
      this.seat37,
      this.seat38,
      this.seat39,
      this.seat40,
      this.seat41,
      this.seat42,
      this.seat43,
      this.seat44});

  get s => null;

  set seat(String seat) {}




}

List<Seats> seatsList = [];
